# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 354d0b4d5475d5c8004b377fd8e49aec7574e8a2ffb3ede474484352955d1722dd8f95fc5c85aa7216a27db4e2752ff4c3de03a4b605c354685605c67fdaaa00

test:
  secret_key_base: 1d7f62bf5bdbbd7d05f6f5338295b94596bcd0169fd9263c937e1287750d381820725a0b7bc91baaa9a532442b0f4b36b6327fe45d3db41fd47def35d9f304a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
